trigger:
- none

pool: 
  name: Default
  
steps:
- task: Docker@2
  displayName: Build Docker Image
  inputs:
    containerRegistry: 'Docker Registry'
    repository: '338121/web-app'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    
- task: Docker@2
  displayName: Push Docker Image
  inputs:
    containerRegistry: 'Docker Registry'
    repository: '338121/web-app'
    command: 'push'
    