trigger:
- none

pool: 
  name: Default
  
steps:
- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'
- task: ECRPushImage@1
  inputs:
    awsCredentials: 'aws account'
    regionName: 'us-east-1'
    repositoryName: $(repositoryName)
    pushTag: '$(Build.BuildId)'
    