apiVersion: apps/v1
kind: Deployment
metadata:
  name: qi-site
  namespace: qi
  labels:
    app: webserver
    tier: app
    project: onlineshop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
      tier: app
      project: onlineshop
  template:
    metadata:
      labels:
        app: webserver
        tier: app
        project: onlineshop
    spec:
      containers:
      - name: webserver
        imagePullPolicy: Always
        image: 338121/webserver:v2
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"