apiVersion: apps/v1
kind: Deployment
metadata:
  name: qi-site
  labels:
    app: webserver
    tier: app
    project: onlineshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
      tier: app
      project: onlineshop
  template:
    metadata:
      labels:
        app: webserver
        tier: app
        project: onlineshop
    spec:
      containers:
      - name: webserver
        image: 338121/webserver:v1
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    app: webserver
    tier: app
    project: onlineshop
spec:
  type: LoadBalancer
  selector:
  # you should provide pod labels here
    app: webserver
    tier: app
    project: onlineshop
  ports:
  - name: webport-port
    protocol: TCP
    port: 80
    targetPort: 80