apiVersion: apps/v1
kind: Deployment
metadata:
  name: qi-site
  labels:
    app: webserver
    tier: app
    project: onlineshop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
      tier: app
      project: onlineshop
  template:
    metadata:
      labels:
        app: webserver
        tier: app
        project: onlineshop
    spec:
      containers:
      - name: webserver
        imagePullPolicy: Always
        image: 338121/webserver:v2