apiVersion: v1
kind: Service
metadata:
  name: qi-service
  namespace: web-app
  labels:
    app: webserver
    tier: app
    project: onlineshop
spec:
  type: LoadBalancer
  selector:
  # you should provide pod labels here
    app: webserver
    tier: app
    project: onlineshop
  ports:
  - name: webport-port
    protocol: TCP
    port: 80
    targetPort: 80